"""empty message

Revision ID: 8f62e4297a0f
Revises: 
Create Date: 2018-01-28 22:49:07.220421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f62e4297a0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_flask_learn_guild',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_name', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_flask_learn_guild_country_code'), 't_flask_learn_guild', ['country_code'], unique=False)
    op.create_index(op.f('ix_t_flask_learn_guild_guild_name'), 't_flask_learn_guild', ['guild_name'], unique=True)
    op.create_table('t_flask_learn_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('skill_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_flask_learn_item_item_name'), 't_flask_learn_item', ['item_name'], unique=True)
    op.create_index(op.f('ix_t_flask_learn_item_skill_points'), 't_flask_learn_item', ['skill_points'], unique=False)
    op.create_table('t_flask_learn_play_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_flask_learn_play_item_item_id'), 't_flask_learn_play_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_t_flask_learn_play_item_player_id'), 't_flask_learn_play_item', ['player_id'], unique=False)
    op.create_table('t_flask_learn_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('skill_points', sa.Integer(), nullable=True),
    sa.Column('guild_id', sa.Integer(), nullable=True),
    sa.Column('regist_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_flask_learn_player_email'), 't_flask_learn_player', ['email'], unique=True)
    op.create_index(op.f('ix_t_flask_learn_player_guild_id'), 't_flask_learn_player', ['guild_id'], unique=False)
    op.create_index(op.f('ix_t_flask_learn_player_nickname'), 't_flask_learn_player', ['nickname'], unique=True)
    op.create_index(op.f('ix_t_flask_learn_player_skill_points'), 't_flask_learn_player', ['skill_points'], unique=False)
    op.create_table('t_flask_learn_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_flask_learn_user_email'), 't_flask_learn_user', ['email'], unique=True)
    op.create_index(op.f('ix_t_flask_learn_user_username'), 't_flask_learn_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_flask_learn_user_username'), table_name='t_flask_learn_user')
    op.drop_index(op.f('ix_t_flask_learn_user_email'), table_name='t_flask_learn_user')
    op.drop_table('t_flask_learn_user')
    op.drop_index(op.f('ix_t_flask_learn_player_skill_points'), table_name='t_flask_learn_player')
    op.drop_index(op.f('ix_t_flask_learn_player_nickname'), table_name='t_flask_learn_player')
    op.drop_index(op.f('ix_t_flask_learn_player_guild_id'), table_name='t_flask_learn_player')
    op.drop_index(op.f('ix_t_flask_learn_player_email'), table_name='t_flask_learn_player')
    op.drop_table('t_flask_learn_player')
    op.drop_index(op.f('ix_t_flask_learn_play_item_player_id'), table_name='t_flask_learn_play_item')
    op.drop_index(op.f('ix_t_flask_learn_play_item_item_id'), table_name='t_flask_learn_play_item')
    op.drop_table('t_flask_learn_play_item')
    op.drop_index(op.f('ix_t_flask_learn_item_skill_points'), table_name='t_flask_learn_item')
    op.drop_index(op.f('ix_t_flask_learn_item_item_name'), table_name='t_flask_learn_item')
    op.drop_table('t_flask_learn_item')
    op.drop_index(op.f('ix_t_flask_learn_guild_guild_name'), table_name='t_flask_learn_guild')
    op.drop_index(op.f('ix_t_flask_learn_guild_country_code'), table_name='t_flask_learn_guild')
    op.drop_table('t_flask_learn_guild')
    # ### end Alembic commands ###
